name: Setup labels

permissions:
  contents: write
  issues: write
  actions: write

on:
  push:
    branches:
      - main
  repository_dispatch:  # Permite disparar manualmente

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout do repositório
      - name: Check out repository
        uses: actions/checkout@v3

      # 2️⃣ Aplicar labels usando EndBug/label-sync
      - name: Apply labels
        uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels/labels.yml
          token: ${{ secrets.LABELS_TOKEN }}
          delete-other-labels: false
